file:
    - 'tests/functional/api/users/index.test.js'
    - 'tests/functional/api/movies/index.test.js'
    - 'tests/functional/api/tmdb/index.test.js'
require: '@babel/register'
exit: true
timeout: 6000
